version: '3.0'

services:
  tile38:
    image: tile38/tile38
    ports:
      - "9851:9851"
      - "9852:9852"
    volumes:
      - ./data:/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "2110:2110"
    depends_on:
      - redis
      - tile38